# Generated by Django 4.1 on 2022-08-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerMVT', '0003_familia_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='edad',
        ),
    ]
