# Generated by Django 4.1 on 2022-08-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerMVT', '0004_remove_familia_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
