# Generated by Django 4.1 on 2022-08-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimerMVT', '0005_familia_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='fechanac',
            field=models.DateField(null=True),
        ),
    ]
